AdventCalendar/config/routes.rb
AdventCalendar::Application.routes.draw do

  get "admin/index"

  get "admin/show_users"

  devise_for :users

  resources :doors
  resources :users
  resources :calendars

  root :to => 'calendars#index'

end

AdventCalendar/app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :doors, :dependent => :destroy

  belongs_to :user
  has_and_belongs_to_many :users

  validates_presence_of :title

end

AdventCalendar/app/models/door.rb
class Door < ActiveRecord::Base
  belongs_to :calendar

  validates_presence_of :content
end

AdventCalendar/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :surname, :id, :admin

  validates_presence_of :name, :surname

  has_many :calendars, :dependent => :destroy
  has_and_belongs_to_many :calendars

end

AdventCalendar/app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :check_if_admin

  protected

  def check_if_admin
    unless user_signed_in? && current_user.admin?
      redirect_to root_path, alert: 'You do not have permission to access this part of the website!'
    end
  end

  public

  def index
    @calendars = Calendar.all
    @users = User.all
  end

  def show_users

    name = "%#{params[:n]}%"
    surname = "%#{params[:sn]}%"

    @users = User.where("name LIKE ? AND surname LIKE ?", name, surname)

    if @users.size == 1
      redirect_to @users.first
    end

  end

end

AdventCalendar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

AdventCalendar/app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
    @users = User.all

    if user_signed_in?

      @shared_calendars = current_user.calendars

      @user_calendars = Calendar.find_all_by_user_id(current_user.id)

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendars }
    end
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    @calendar = Calendar.find(params[:id])

    unless @calendar.public?
      if user_signed_in?
        unless @calendar.user_id == current_user.id || current_user.calendars.includes(@calendar)
          redirect_to root_path, alert: 'You do not have permission to access this calendar!' and return
        end
      else
        redirect_to root_path, alert: 'You have to log in before you can access a private calendar' and return
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/new
  # GET /calendars/new.json
  def new
    @calendar = Calendar.new

    @users = User.where("id <> #{current_user.id}")

    24.times { @calendar.doors.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/1/edit
  def edit
    @calendar = Calendar.find(params[:id])
    @users = User.where("id <> #{current_user.id}")
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(params[:calendar])
    @calendar.update_attribute :user_id, current_user.id

    params[:doors].each_value do |door|
      @calendar.doors.build(door)
    end

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render json: @calendar, status: :created, location: @calendar }
      else
        format.html { render action: "new" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calendars/1
  # PUT /calendars/1.json
  def update
    @calendar = Calendar.find(params[:id])

    @calendar.doors.destroy_all
    params[:doors].each_value do |door|
      @calendar.doors.build(door)
    end

    @calendar.user_ids = params[:user_ids]

    respond_to do |format|
      if @calendar.update_attributes(params[:calendar])
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

AdventCalendar/app/controllers/doors_controller.rb
class DoorsController < ApplicationController

  before_filter :check_open_date

  def show
    @calendar = Calendar.find(@door.calendar_id)

    unless @calendar.public?
      if user_signed_in?
        unless @calendar.user_id == current_user.id || current_user.admin?
          redirect_to root_path, alert: "You are not allowed to access that part of the site!"
        end
      else
        redirect_to root_path, alert: "You have to be signed in before you can access that part of the site!!"
      end
    end
  end

  private

  def check_open_date
    @door = Door.find(params[:id])
    if @door.unlock_date.future?
      redirect_to root_path, notice: "You cannot open this door yet!"
    end
  end

end

AdventCalendar/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :validate_access

  def validate_access
    unless user_signed_in?
      redirect_to root_path, alert: 'You have to log in to be able to access that part of the website' and return
    end

    unless current_user.admin?
      redirect_to root_path, alert: 'You do not have access to that part of the website'
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendars }
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])

    if @user == current_user
      redirect_to @user, alert: 'Please use the link in the panel named "Edit my account" to edit your own user.'
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update

    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    @user = User.find(params[:id])


    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

AdventCalendar/app/helpers/admin_helper.rb
module AdminHelper

  # Returns owner of given calendar

  #  Example use: put "#{owner_of(@calendar).name}"

  def owner_of(calendar)
    users = User.all

    for user in users.each do
      return user if user.id == calendar.user_id
    end
  end
end

AdventCalendar/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns true if used has access to given calendar, returns false in all other cases

  # Example use: "user_has_access_to? @calendar"

  def user_has_access_to?(calendar)
    access = false
    if user_signed_in?
      if current_user.admin? || current_user.id == calendar.user_id
        access = true
      end
    end

    access
  end

  # Returns true if signed in user is admin, returns false in all other cases

  # Example use: "if user_is_admin?"

  def user_is_admin?
    if user_signed_in?
      current_user.admin?
    else
      false
    end
  end

end

AdventCalendar/app/helpers/calendars_helper.rb
module CalendarsHelper
end

AdventCalendar/app/helpers/doors_helper.rb
module DoorsHelper
end

AdventCalendar/app/helpers/users_helper.rb
module UsersHelper
end

AdventCalendar/app/views/admin/_calendar.html.erb
<tr>
  <td><%= link_to "#{calendar.title}", calendar %></td>
  <td>
    <% if calendar.public? %>
        <p>Public</p>
    <% else %>
        <p>Private</p>
    <% end %>
  </td>
  <td><%= link_to "#{owner_of(calendar).name} #{owner_of(calendar).surname}", owner_of(calendar) %></td>
</tr>

AdventCalendar/app/views/admin/_form.html.erb
<%= form_tag({:controller => "admin", :action => "show_users"}, :method => "get") do %>
    <div class="field">
      <%= label_tag(:n, "Name:") %>
      <%= text_field_tag(:n) %>
    </div>

    <div class="field">
      <%= label_tag(:sn, "Surname:") %>
      <%= text_field_tag(:sn) %>
    </div>

    <h6>(Leave blank to get all users)</h6>

    <div class="actions">
      <%= submit_tag("Search") %>
    </div>
<% end %>

AdventCalendar/app/views/admin/_user.html.erb
<tr>
  <td><%= link_to "#{user.name} #{user.surname}", user %></td>
</tr>

AdventCalendar/app/views/admin/index.html.erb
<%= render :partial => 'admin/form' %>

<h2>All calendars</h2>

<table>

  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Owner</th>
  </tr>

  <%= render :partial => 'admin/calendar', :collection => @calendars %>
</table>

AdventCalendar/app/views/admin/show_users.html.erb
<table>
  <tr>
    <% unless @users.empty? %>
        <%= render :partial => 'admin/user', :collection => @users %>
    <% else %>
        <p>Could not find any users by your search criteria.</p>
    <% end %>
  </tr>
</table>

<br/>

<%= link_to "Back", admin_index_path %>

AdventCalendar/app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>

    <% if @calendar.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

          <ul>
            <% @calendar.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :img_url %>
      <br/>
      <%= f.text_field :img_url %>
    </div>

    <div class="field">
      <%= f.label 'Make public:' %>
      <br/>
      <%= f.check_box :public, {}, true, false %>
    </div>

    <div class="field">
      <%= f.label 'Share with user:' %>
      <br/>
      <ul>
        <% for user in @users do %>
            <li>
              <%= check_box_tag 'calendar[user_ids][]',
                                user.id,
                                @calendar.user_ids.include?(user.id),
                                :id => "user_#{user.id}"
              %>
              <%= label_tag "user_#{user.id}", user.name %>
            </li>
        <% end %>
      </ul>
    </div>


    <div class="field">
      <table border="5" title="<%= @calendar.title %>">
        <tr>
          <% @calendar.doors.each_with_index do |door, index| %>
              <td>
                <%= fields_for "doors[#{index}]", door do |g| %>
                    <p><%= "#{index + 1}.Desember" %></p>
                    <p><%= g.text_area :content, :cols => 20, :rows => 5 %></p>

                    <!-- Adding a hidden unlock-date -->
                    <%= g.hidden_field :unlock_date, {:value => ("#{index + 1}-12-#{Time.now.year}")} %>
                <% end %>
              </td>
              <% if (index + 1) % 4 == 0 %>
                  </tr>
                  <tr>
              <% end %>
          <% end %>
          </tr>
          </table>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

AdventCalendar/app/views/calendars/_public_calendars.html.erb
<% @calendars.each do |calendar| %>
    <tr>
      <% if calendar.public? %>
          <td><%= link_to "#{calendar.title}", calendar %></td>
          <td><%= calendar.user.name %></td>
          <% if user_is_admin? %>
              <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
              <td><%= link_to 'Destroy', calendar, confirm: 'Are you sure?', method: :delete %></td>
          <% end %>
      <% end %>
    </tr>
<% end %>

AdventCalendar/app/views/calendars/_shared_calendars.html.erb
<% @shared_calendars.each do |calendar| %>
    <tr>
      <td><p><%= link_to "#{calendar.title}", calendar %></td>
      </p>
      <td><%= calendar.user.name %></td>
      <% if user_is_admin? %>
          <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
          <td><%= link_to 'Destroy', calendar, confirm: 'Are you sure?', method: :delete %></td>
      <% end %>
    </tr>
<% end %>

AdventCalendar/app/views/calendars/_show_doors.html.erb
<tr>
  <% @calendar.doors.each_with_index do |door, index| %>
      <td>
        <% unless door.unlock_date.future? %>
            <%= link_to "#{index + 1}", door %>
        <% else %>
            <b><%= index + 1 %></b>
        <% end %>
      </td>
      <% if (index + 1) % 4 == 0 %>
          </tr>
          <tr>
      <% end %>
  <% end %>
  </tr>

AdventCalendar/app/views/calendars/_your_calendars.html.erb
<% @user_calendars.each do |calendar| %>
    <tr>
      <td><p><%= calendar.title %></td>
      </p>
      <td>
        <% if calendar.public? %>
            <p>Public</p>
        <% else %>
            <p>Private</p>
        <% end %>
      </td>
      <td><%= link_to 'Show', calendar %></td>
      <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
      <td><%= link_to 'Destroy', calendar, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>

AdventCalendar/app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

AdventCalendar/app/views/calendars/index.html.erb
<table>

  <!-- Official  calendars, unless empty/missing-->
  <tr>
    <h2>Public Calendars</h2>

    <% unless @calendars.empty? %>
        <table>
          <tr>
            <th>Title</th>
            <th>Owner</th>
          </tr>

          <%= render 'calendars/public_calendars' %>

        </table>
    <% else %>
        <p>No calendars available</p>
    <% end %>

  </tr>
  <br/><br/>

  <!-- Calendars shared with user, unless empty/missing, or not signed in -->
  <% if user_signed_in? %>
      <tr>
        <h2>Shared Calendars</h2>

        <% unless @shared_calendars.empty? %>
            <table>
              <tr>
                <th>Title</th>
                <th>Owner</th>
              </tr>

              <%= render 'calendars/shared_calendars' %>

            </table>
        <% else %>
            <p>No calendars available</p>
        <% end %>

      </tr>
      <br/><br/>

      <!-- Users calendars, unless empty/missing, or not signed in-->
      <tr>
        <h2>Your Calendars</h2>

        <% unless @user_calendars.empty? %>
            <table>
              <tr>
                <th>Title</th>
                <th>Status</th>
              </tr>

              <%= render 'calendars/your_calendars' %>

            </table>
        <% else %>
            <p>No calendars available</p>
        <% end %>
        <br/>

        <%= link_to 'New Calendar', new_calendar_path %>
      </tr>
  <% end %>

</table>

AdventCalendar/app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

AdventCalendar/app/views/calendars/show.html.erb
<p>
  <b>Title:</b>
  <%= @calendar.title %>
</p>

<p>
  <b>Public:</b>
  <% if @calendar.public? %>
      Yes
  <% else %>
      No
  <% end %>
</p>

<table border="5" cellpadding="50"

       <% if !@calendar.img_url.nil? %>
       background="<%= @calendar.img_url %>"
       <% else %>
       bgcolor="#AA1100"
       <% end %>

       title="<%= @calendar.title %>">

  <%= render :partial => 'calendars/show_doors' %>

</table>

<br/>

<% if user_has_access_to? @calendar %>
    <%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<% end %>

<%= link_to 'Back', calendars_path %>

AdventCalendar/app/views/doors/show.html.erb
<h2><b><%= @calendar.title %></b></h2>

<h4><b>Date: (<%= @door.unlock_date %>)</b></h4>

<h5><b>Content: </b></h5>
<p><%= @door.content %></p>

<br/>
<%= link_to 'Back', @calendar %>

AdventCalendar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdventCalendar</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>AdventCalendar</h1>
<h5>Make your own calendar and share it with friends and family!</h5>
<table border="1">
  <tr>
    <td><%= link_to "Home", root_path %></td>
    <% if user_signed_in? %>
        <td>Signed in as <%= current_user.name %> <%= current_user.surname %>.</td>
        <td><%= link_to "Edit my account", edit_user_registration_path, :request => :get %></td>
        <td><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></td>
        <% if current_user.admin? %>
            <td><%= link_to "Admin-panel", admin_index_path %></td>
        <% end %>
    <% else %>
        <td><%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %></td>
    <% end %>
  </tr>
</table>

<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>

<br/>

<%= yield %>

</body>
</html>

AdventCalendar/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %>
      <br/>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br/>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <br/>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :surname %>
      <br/>
      <%= f.text_field :surname %>
    </div>

    <div class="field">
      <p><%= f.label 'Role:' %><br/></p>

      <p><%= f.radio_button :admin, true %>Admin</p>

      <p><%= f.radio_button :admin, false %>User</p>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

AdventCalendar/app/views/users/_user.html.erb
<tr>
  <td><%= user.email %></td>
  <td><%= user.name %></td>
  <td><%= user.surname %></td>
  <td>
    <% if user.admin %>
        Admin
    <% else %>
        User
    <% end %>
  </td>
  <td><%= link_to 'Show', user %></td>
  <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
  <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
</tr>

AdventCalendar/app/views/users/edit.html.erb
<%= render 'users/form' %>

<%= link_to 'Destroy user', @user, confirm: 'Are you sure?', method: :delete %>
<%= link_to 'Back', @user %>

AdventCalendar/app/views/users/index.html.erb
<table>
  <tr>
    <th>email</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <%= render :partial => 'users/user', :collection => @users %>
</table>

AdventCalendar/app/views/users/show.html.erb
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Surname:</b>
  <%= @user.surname %>
</p>

<p>
  <b>Role:</b>
  <% if @user.admin? %>
      Admin
  <% else %>
      User
  <% end %>
</p>

<% if current_user.admin? %>
    <%= link_to 'Edit', edit_user_path(@user) %>
    <%= link_to 'Back', admin_index_path %>
<% end %>